name: Fortnite Rank Scraper

on:
  push:
    branches:
      - main  # Change this to your default branch name if different
  schedule:
    - cron: '* * * * *'  # Run every hour

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium requests

      - name: Run scraper
        run: python main.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    env:
      max-runs: 10
